/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.views.dialogs;

import com.sv.udb.models.Authority;
import com.sv.udb.utilities.Animations;

/**
 *
 * @author kevin
 */
public class SearchAuthority extends javax.swing.JPanel {

    /**
     * Autoridad seleccionada, variable a retornar
     */
    Authority auth;
    
    /**
     * Creates new form SearchAuthority
     */
    public SearchAuthority() {
        initComponents();
        Animations.initStyle(this);
    }
    
    /**
     * Método a llamar desde el frame padre luego de dar OK en el dialog
     * @return 
     */
    public Authority getValue() {
        return auth;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        cmbAuthSearchType = new javax.swing.JComboBox<>();
        txtAuthSearch = new javax.swing.JTextField();
        btnAuthSearchReset = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblAuth = new javax.swing.JTable();

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Autoridades");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Buscar por:");

        cmbAuthSearchType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbAuthSearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "N/A" }));
        cmbAuthSearchType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAuthSearchTypeActionPerformed(evt);
            }
        });

        txtAuthSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAuthSearch.setForeground(new java.awt.Color(6, 43, 51));

        btnAuthSearchReset.setBackground(new java.awt.Color(121, 121, 101));
        btnAuthSearchReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAuthSearchReset.setForeground(new java.awt.Color(255, 255, 255));
        btnAuthSearchReset.setText("Revertir");
        btnAuthSearchReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tblAuth.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ));
        tblAuth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAuthMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblAuth);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addComponent(jScrollPane5)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(cmbAuthSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(txtAuthSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnAuthSearchReset))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cmbAuthSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAuthSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAuthSearchReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAuthSearchTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAuthSearchTypeActionPerformed
        if (cmbAuthSearchType.getSelectedIndex() == 1)
            txtAuthSearch.setVisible(false);
        else 
            txtAuthSearch.setVisible(true);
    }//GEN-LAST:event_cmbAuthSearchTypeActionPerformed

    private void tblAuthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAuthMouseClicked
        auth = (Authority) tblAuth.getValueAt(tblAuth.getSelectedRow(), 0);
    }//GEN-LAST:event_tblAuthMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuthSearchReset;
    private javax.swing.JComboBox<String> cmbAuthSearchType;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable tblAuth;
    private javax.swing.JTextField txtAuthSearch;
    // End of variables declaration//GEN-END:variables
}
